### ISSUE TITLE
ImplicitMPM - GPU memory keeps growing per step

### ISSUE THREAD

**Issue by Cucchi01** [newton-physics/newton#1042]
### ImplicitMPM - GPU memory keeps growing per step

After several minutes of training, the GPU memory usage continuously increases until all available memory is exhausted.

It's unclear to us (people working on this at ETH RSL Lab) why the memory grows gradually instead of triggering an immediate out-of-memory error.
To help reproduce, I have created a minimal example that replicates the behavior.
[example_mpm_memory_issue.py](https://github.com/user-attachments/files/23393659/example_mpm_memory_issue.py)

**Environment**
- Script: `newton/newton/examples/mpm/example_mpm_memory_issue.py` (created and shared in this issue)
- GPU: NVIDIA RTX 3060 (12 GiB)
- Additional deps (installed via `uv add`):
  - matplotlib
  - nvidia-ml-py
  - psutil
  
- nvidia-smi
```  
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   [REDACTED]  On |                  N/A |
|  0%   53C    P8             17W /  170W |     660MiB /  12288MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   [REDACTED]      G   /usr/lib/xorg/Xorg                            182MiB |
|    0   N/A  N/A   [REDACTED]    C+G   ...libexec/gnome-remote-desktop-daemon        104MiB |
|    0   N/A  N/A   [REDACTED]      G   /usr/bin/gnome-shell                           97MiB |
|    0   N/A  N/A   [REDACTED]      G   ...irefox/7177/usr/lib/firefox/firefox        139MiB |
|    0   N/A  N/A   [REDACTED]      G   /usr/share/code/code                           99MiB |
|    0   N/A  N/A   [REDACTED]      G   /usr/bin/gnome-control-center                  11MiB |
|    0   N/A  N/A   [REDACTED]      G   /usr/bin/gjs-console                            4MiB |
+-----------------------------------------------------------------------------------------+
```

**How to reproduce**
```bash
uv run newton/newton/examples/mpm/example_mpm_memory_issue.py          # headless
uv run newton/newton/examples/mpm/example_mpm_memory_issue.py --viewer # optional visualization
```

With this example code [example_mpm_memory_issue.py](https://github.com/user-attachments/files/23393659/example_mpm_memory_issue.py)

### Observations
step 1 cpu= 760.60 MiB gpu= 1278.47 MiB
step 2 cpu= 762.60 MiB gpu= 1502.47 MiB
step 3 cpu= 762.72 MiB gpu= 1630.47 MiB
step 4 cpu= 762.72 MiB gpu= 1694.47 MiB
step 5 cpu= 762.72 MiB gpu= 1726.47 MiB
step 6 cpu= 762.72 MiB gpu= 1822.47 MiB
step 7 cpu= 762.85 MiB gpu= 1920.47 MiB
step 8 cpu= 762.85 MiB gpu= 2016.47 MiB

.......
step 892 cpu= 766.60 MiB gpu= 10880.47 MiB
step 893 cpu= 766.60 MiB gpu= 10912.47 MiB
step 894 cpu= 766.60 MiB gpu= 10880.47 MiB
step 895 cpu= 766.60 MiB gpu= 10880.47 MiB
step 896 cpu= 766.60 MiB gpu= 10912.47 MiB
Warp CUDA error 2: out of memory (in function wp_alloc_device_async, /builds/omniverse/warp/warp/native/warp.cu:657)
Traceback (most recent call last):
File "....../example_mpm_memory_issue.py", line 163, in <module>
main()
File "....../example_mpm_memory_issue.py", line 141, in main
solver.step(state_0, state_1, None, None, DT)
File "....../newton/newton/_src/solvers/implicit_mpm/solver_implicit_mpm.py", line 1666, in step
self._step_impl(state_in, state_out, dt, self._scratchpad)
File "....../newton/newton/_src/solvers/implicit_mpm/solver_implicit_mpm.py", line 2326, in _step_impl
"u": scratch.velocity_trial,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/fem/integrate.py", line 1805, in integrate
return _launch_integrate_kernel(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/fem/integrate.py", line 1476, in _launch_integrate_kernel
triplet_values_temp = cache.borrow_temporary(
^^^^^^^^^^^^^^^^^^^^^^^
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/fem/cache.py", line 619, in borrow_temporary
Temporary(shape=shape, dtype=dtype, pinned=pinned, device=device, requires_grad=requires_grad)
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/types.py", line 2434, in init
self._init_new(dtype, shape, strides, device, pinned)
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/types.py", line 2829, in _init_new
ptr = allocator.alloc(capacity)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "....../newton/.venv/lib/python3.11/site-packages/warp/_src/context.py", line 2706, in alloc
raise RuntimeError(f"Failed to allocate {size_in_bytes} bytes on device '{self.device}'")
RuntimeError: Failed to allocate 147456000 bytes on device 'cuda:0'

### Expectations
With a fixed world/particle count, successive timesteps should reuse GPU buffers so memory stays roughly flat.

### Actual
Tested with both `fixed` and `sparse` grid_type and in both cases the program eventually crashes. 

### Notes
When `PARTICLES_PER_WORLD=4`, the memory usage increases up to a certain point, then drops, and starts increasing again when the `grid_type` is set to `sparse`. In contrast, with `grid_type=fixed`, the memory usage remains constant after a first increase.

<img width="960" height="720" alt="Image" src="https://github.com/user-attachments/assets/54dd7dc6-ee7a-4224-8398-852c0c9d9237" />

<img width="960" height="720" alt="Image" src="https://github.com/user-attachments/assets/9e860cfd-bf59-4e00-b9c7-99f9f21289c1" />

**Comment by gdaviet** [comment]
I can reproduce the issue. It would be good to understand why this is required, but as a workaround forcing garbage collection using `gc.collect()` works:
( This is what I get without:
```
step    100 cpu=   732.22 MiB gpu=  3272.00 MiB
step    200 cpu=   732.79 MiB gpu=  4488.00 MiB
step    300 cpu=   733.21 MiB gpu=  5832.00 MiB
step    400 cpu=   733.63 MiB gpu=  7048.00 MiB
step    500 cpu=   733.91 MiB gpu=  8232.00 MiB
```
 and with explicit `gc.collect()` every 10 step:
```
step    100 cpu=   607.15 MiB gpu=  2312.00 MiB
step    200 cpu=   607.15 MiB gpu=  2312.00 MiB
step    300 cpu=   607.15 MiB gpu=  2312.00 MiB
step    400 cpu=   607.15 MiB gpu=  2312.00 MiB
step    500 cpu=   607.15 MiB gpu=  2312.00 MiB
step    600 cpu=   607.15 MiB gpu=  2312.00 MiB
step    700 cpu=   607.15 MiB gpu=  2312.00 MiB
step    800 cpu=   607.15 MiB gpu=  2312.00 MiB
step    900 cpu=   607.15 MiB gpu=  2312.00 MiB
```

Alternatively, if you're using a "fixed" grid with >0 `mpm_options.max_grid_cell_count` you can graph-capture the mpm step (see examples in `mpm/example_mpm_twoway_coupling.py` or `mpm/example_mpm_anymal.py`. Then GPU memory will be allocated once when capturing the graph, then should not increase afterwards



Edit: I am seeing some "nans" with grid_type="fixed", which is likely an unrelated issue, but in the meantime I'd suggest sticking to grid_type="sparse" + explicit gc collect

**Comment by gdaviet** [comment]
The issue with the fixed grid is related to elastic particles; I'll will fix it, but in the meantime I suggest disabling elasticity by setting `particle_ke` to a very large value (note that it used to be that particles where inelastic by default; now they read the value from the model. For granular materials you probably want to always overwrite the `particle_ke` to something >= 1.e12.

The was also a regression with warm-starting graph-captured steps, I'll open a PR with the fix.

With that fixed it works pretty well (much faster, and stable memory usage)

https://github.com/user-attachments/assets/dde22f53-5730-49ae-b084-97e34fcac426

```
step    100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step    900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   1900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   2900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   3900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   4900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   5900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   6900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   7900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   8900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9000 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9100 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9200 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9300 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9400 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9500 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9600 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9700 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9800 cpu=  1241.55 MiB gpu=  7142.00 MiB
step   9900 cpu=  1241.55 MiB gpu=  7142.00 MiB
step  10000 cpu=  1241.55 MiB gpu=  7142.00 MiB
```

Script with grah-capture on: 
[example_mpm_memory_issue.py](https://github.com/user-attachments/files/23422352/example_mpm_memory_issue.py)

**Comment by Cucchi01** [comment]
Thank you very much for your quick help and suggestions @gdaviet !

I investigated the problem, and I think that with `sparse` it may be connected to `temporary_store` and the need for an explicit release, similar to PR #1030 .

Exactly like in the mentioned PR, in many places in the `warp` repository (where `borrow_temporary` or `borrow_temporary_like` is used), `.release()` is not called explicitly on `Temporary`. As a result, until the garbage collector is invoked, the GPU memory is not actually released, and new memory is allocated at each iteration by the `temporary_store`.

For example, if I call `solver.temporary_store.clear()` and `gc.collect()` in the example I shared, the GPU memory usage goes down.  
While if I just call `gc.collect()` but not `solver.temporary_store.clear()`:
- it does not decrease because the pool does not clear the memory
- it does not increase because the pool can reuse the memory that is released

Both:
<img width="1188" height="950" alt="Image" src="https://github.com/user-attachments/assets/7e301a4c-f543-417a-8ebf-98d9a1a2a9d6" />

gc.collect() only:
<img width="1188" height="950" alt="Image" src="https://github.com/user-attachments/assets/87cef6a0-38f4-457e-a8ac-0c39bdaf06a9" />

The same cyclic/self-reference problem may be present in other places that I am not aware of, keeping the memory allocated until `gc.collect()` removes them in `warp`.

I started fixing this in `warp`, but there are many places where `Temporary` is borrowed (including those where `Temporary` is returned to other components).  
I could open an issue in `warp` if you agree that the problem is what I mentioned.

I also considered using `weakref` for `self.array = temporary` in `cache.py` (so it does not count as a real reference and the memory is released when the variable goes out of scope), but I don’t think it is a viable solution since it may not be compatible with the `@kernel`. There may be other alternative to keep back-compatibility that I may missing.

Another mostly unrelated thing I noticed is that the solver does not reuse the `temporary_store` for all functions calls like:
```
                fem.interpolate(
                    collider_gradient_field,
                    dest=fem.make_restriction(
                        scratch.collider_normal_field, space_restriction=scratch.velocity_test.space_restriction
                    ),
                    fields={"distance": scratch.collider_distance_field},
                    values={"voxel_size": self.mpm_model.voxel_size},
                )
```
could be:

```
                fem.interpolate(
                    collider_gradient_field,
                    dest=fem.make_restriction(
                        scratch.collider_normal_field, space_restriction=scratch.velocity_test.space_restriction
                    ),
                    fields={"distance": scratch.collider_distance_field},
                    values={"voxel_size": self.mpm_model.voxel_size},
                      temporary_store=self.temporary_store,
                )
```
I have to investigate this further, but if you agree this second thing is a problem I can open a PR solving this in Newton.

**Comment by Cucchi01** [comment]
Hi @gdaviet, I write this just to share a quick update.
  
I now have a Warp PR open that adds explicit releases for FEM temporaries; when I rerun `example_mpm_memory_issue.py` with those Warp changes the run stays far flatter (GPU 2.0 → 10.4 GiB over 2.6k steps vs 3.3 → 10.4 GiB by step 800), so the fix looks beneficial for this issue, but does not solve completely the issue alone for `sparse`.

The runs are done with some changes also in Newton. Main differences:

- `newton/_src/solvers/implicit_mpm/solver_implicit_mpm.py`
  - `_ImplicitMPMScratchpad` added a `__del__` guard plus `_release_temp_attr()` helper so any borrowed Warp arrays are deterministically returned.
  - added a `build_temporaries()` that drops old buffers before borrowing new ones, preventing self-referential temporaries from surviving across steps.
  - Bounds computation path now reuses temporary-store helpers and releases buffers right after use.
  - Pass the temporary_store to the function like fem.integrate and when needed release the Temporary resulting from integrate

I still need to clean those Newton changes up and then I will add them either as a follow-up PR or adding them to the existing one in Newton, but I wanted to share the effects of the Warp-side PR
